export const CAMBIAR_MODO_OSCURO = "CAMBIAR_MODO_OSCURO";
export const CAMBIAR_COLOR_TEMA = "CAMBIAR_COLOR_TEMA";

export const OBTENER_MODO_OSCURO = "OBTENER_MODO_OSCURO";
export const OBTENER_COLOR_TEMA = "OBTENER_COLOR_TEMA";